---
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: awx.awx
  - name: containers.podman
  # - name: containers.docker
  - name: kubernetes.core
  - name: redhatinsights.insights
  - name: community.general
    source: https://old-galaxy.ansible.com
  - name: community.crypto
  - name: community.kubevirt
