before_script:
  - apt -y update && apt -y upgrade
  - apt install python3 python3-dev python3-cryptography curl autoconf automake gcc git python3-pip
  - pip install --upgrade pip
  - pip install -r requirements.txt 

stages:
  - test

molecule_test:
  stage: test
  script:
    - molecule test