default:
  image: python:3.11

before_script:
  - pip install --upgrade pip
  - pip install ansible ansible-lint molecule[kubevirt] kubernetes openshift

stages:
  - test

molecule_test:
  stage: test
  script:
    - molecule test