---
  default:
    image: python-3.11
  stages:
    - test
  
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"
    GIT_STRATEGY: clone
  
  cache:
    paths:
      - .pip/
      - virtenv/
  
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv virtenv
    - source virtenv/bin/activate
    - pip install -r requirements.txt
    - ansible --version
    - molecule --version
    - docker --version
  
  molecule:
    stage: test
    script:
      - molecule test
  
  