---
collections:
  - name: kubernetes.core
  - name: community.crypto
  - name: community.general
    source: https://old-galaxy.ansible.com
  - name: community.kubevirt
  - name: community.kubernetes
  - name: ansible.utils
