---
- name: Template Config File
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ rke2_config_file }}"
    mode: "0644"
    owner: root
    group: root
  notify:
    - "Restart rke2"
