---
- name: Fetch file from primary node
  delegate_to: "{{ rke2_primary_node }}"
  ansible.builtin.fetch:
    src: "{{ rke2_kubeconfig }}"
    dest: "{{ playbook_dir }}/"
    flat: true

- name: Blcok Test Ready state
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  block:
    - name: Ensure localhost is replaced
      connection: local
      delegate_to: localhost
      become: false
      ansible.builtin.replace:
        path: "{{ playbook_dir }}/rke2.yaml"
        regexp: '(.*)127.0.0.1(.*)'
        replace: '\1{{ rke2_cluster_fqdn }}\2'
        mode: "0600"


    - name: Wait til nodes in cluster are ready
      connection: local
      delegate_to: localhost
      register: k8s_ready_state
      become: false
      kubernetes.core.k8s_info:
        kind: node
        wait: true
        kubeconfig: "{{ playbook_dir }}/rke2.yaml"
        label_selectors:
          - 'kubernetes.io/hostname={{ inventory_hostname }}'
        field_selectors:
          - 'status=Ready'
      changed_when: false
      until: k8s_ready_state is success
      retries: 30
      delay: 3
