---
- name: Wait til nodes in cluster are ready
  when: rke2_primary
  register: k8s_ready_state
  kubernetes.core.k8s_info:
    kind: node
    wait: true
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    label_selectors:
      - 'kubernetes.io/hostname={{ inventory_hostname }}'
    field_selectors:
      - 'status=Redy'
  changed_when: false
  until: k8s_ready_state is success
  retries: 60
  delay: 3
