---
- name: Wait til nodes in cluster are ready
  become: true
  delegate_to: "{{ rke2_primary_node }}"
  kubernetes.core.k8s_info:
    kind: node
    wait: true
    kubeconfig: "{{ rke2_kubeconfig }}"
    label_selectors:
      - 'kubernetes.io/hostname={{ inventory_hostname }}'
    field_selectors:
      - 'status=Ready'
  changed_when: false
  until: k8s_ready_state is success
  retries: 30
  delay: 3
