---
# tasks file for rke2
# Include of prpare.yml This file is intendend to handle the Requirements for RKE2
- name: Solve Requirements throupth prepare.yml
  ansible.builtin.include_tasks:
    file: prepare.yml

# Include rkeversion.yml for checking for new Version
- name: Solve Requirements throupth prepare.yml
  ansible.builtin.include_tasks:
    file: rkeversion.yml

# Manage RKE2 on Primary Server node (Master)
- name: Manage RKE2 Server primary
  when: '"server" in rke2_type and rke2_primary'
  block:
    # Include of token.yml for Checking for token file
    - name: Generate token - RKE2 Server
      ansible.builtin.include_tasks:
        file: token.yml

    # Include config yml to Template config.yml for rke2
    - name: Template Config File - RKE2 Server
      ansible.builtin.include_tasks:
        file: config.yml

    # Includes of rke2.yml for Update and Install RKE2
    - name: Install/Update - RKE2 Server
      ansible.builtin.include_tasks:
        file: rke2.yml

    # - name: Fetch kubectle_config
    #   ansible.builtin.fetch:
    #     src: /etc/rancher/rke2/rke2.yaml
    #     dest: '/tmp/rke2.yaml'
    #     flat: true

    # - name: Replace localhost
    #   connection: local
    #   delegate_to: localhost
    #   ansible.builtin.replace:
    #     path: /tmp/rke2.yaml
    #     regexp: '(https://).*(:6443)'
    #     replace: '\1{{ rke2_cluster_fqdn }}\2'

    - name: Ensure Cluster is Ready
      ansible.builtin.include_tasks:
        file: k8s_check.yml

# Manage RKE2 on Primary Server node (Secondary)
- name: Manage RKE2 Server secondary
  when: '"server" in rke2_type and not rke2_primary'
  throttle: 1
  block:

    # Include of token.yml for Checking for token file
    - name: Generate token - RKE2 Server
      ansible.builtin.include_tasks:
        file: token.yml

    # Include config yml to Template config.yml for rke2
    - name: Template Config File - RKE2 Server
      ansible.builtin.include_tasks:
        file: config.yml

    # Includes of rke2.yml for Update and Install RKE2
    - name: Install/Update - RKE2 Server
      ansible.builtin.include_tasks:
        file: rke2.yml

- name: Ensure Cluster is Ready
  ansible.builtin.include_tasks:
    file: k8s_check.yml


# Manage RKE2 on Agent node (Worker)
- name: Manage RKE2 Agent
  when: '"agent" in rke2_type'
  throttle: 1
  block:

    # Include of token.yml
    - name: Generate token - RKE2 Agent
      ansible.builtin.include_tasks:
        file: token.yml

    # Include config yml to Template config.yml for rke2
    - name: Template Config File - RKE2 Agent
      ansible.builtin.include_tasks:
        file: config.yml

      # Includes of rke2.yml for Update and Install RKE2
    - name: Install/Update - RKE2 Agent
      ansible.builtin.include_tasks:
        file: rke2.yml

- name: Ensure Cluster is Ready
  ansible.builtin.include_tasks:
    file: k8s_check.yml
