---
# tasks file for rke2
# Include of prpare.yml This file is intendend to handle the Requirements for RKE2
- name: Solve Requirements throupth prepare.yml
  ansible.builtin.include_tasks:
    file: prepare.yml

# Include rkeversion.yml for checking for new Version
- name: Solve Requirements throupth prepare.yml
  ansible.builtin.include_tasks:
    file: rkeversion.yml

# Manage RKE2 on Primary Server node (Master)
- name: Manage RKE2 Server primary
  when: '"server" in rke2_type and rke2_primary'
  ansible.builtin.include_tasks:
    file: k8s_tasks.yml

# Manage RKE2 on Primary Server node (Secondary)
- name: Manage RKE2 Server secondary
  when: '"server" in rke2_type and not rke2_primary'
  ansible.builtin.include_tasks:
    file: k8s_tasks.yml

# Manage RKE2 on Agent node (Worker)
- name: Manage RKE2 Agent
  when: '"agent" in rke2_type'
  ansible.builtin.include_tasks:
    file: k8s_tasks.yml
