---
# Check and Prepare package Manager
- name: Ensure ansible_pkg_mgr value is set
  when: ansible_pkg_mgr is undefined
  ansible.builtin.setup:
    filter: 'ansible_pkg_mgr'

# This task file is itended to solve Requirements
# Solve issue https://docs.rke2.io/known_issues#firewalld
# Uninstall firewalld if installed

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Ensure Firewalld is stopped
  when: '"firewalld.service" in ansible_facts.services '
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
    daemon_reload: true

# Solve issue https://docs.rke2.io/known_issues#networkmanager
# Check NetworkManager is installed on Debian
- name: Check if NetworkManager is installed
  register: network_manager
  ansible.builtin.stat:
    path: /etc/NetworkManager/conf.d

- name: Verify Canal and Flannel Interface are ignored by NetworkManager
  when: network_manager.stats.isdir
  ansible.builtin.copy:
    content: |
      [keyfile]
      unmanaged-devices=interface-name:cali*;interface-name:flannel*
    dest: /etc/NetworkManager/conf.d/90-rke2-canal.conf
    owner: root
    group: root
    mode: "0644"

# Solve issue https://docs.rke2.io/known_issues#wicked
# Activate IP Forwared
- name: Verify IP Forward is in place
  ansible.builtin.copy:
    content: |
      net.ipv4.conf.all.forwarding=1
      net.ipv6.conf.all.forwarding=1
      net.ipv4.conf.default.rp_filter=1
      net.ipv4.conf.all.rp_filter=1
    dest: /etc/sysctl.d/90-rke2.conf
    owner: root
    group: root
    mode: "0644"

# Solve issue https://docs.rke2.io/known_issues#canal-and-ip-exhaustion
# Install iptables
- name: Ensure task for issue canal-and-ip-exhausion is included
  ansible.builtin.include_tasks:
    file: "prepare_{{ ansible_pkg_mgr }}.yml"

# Create Directory for Config
- name: Create conifuguration Directory
  ansible.builtin.file:
    path: "{{ rke2_config_path }}"
    mode: "0755"
    owner: root
    group: root
    state: directory
