---
# This task file is itended to solve Requirements
- name: Update Cache
  register: apt_cache_update
  changed_when: apt_cache_update is failed
  ansible.builtin.apt:
    update_cache: true

- name: Ensure firewalld is is Uninstalled
  ansible.builtin.apt:
    name: firewalld
    state: absent

- name: Install and load kubctl package
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Load sources
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install iptables
  ansible.builtin.apt:
    name:
      - iptables
      - ca-certificates
      - apt-transport-https
      - curl
      - wget
      - pgpgpg
      - python3-kubernetes
    state: present

- name: Install Kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present
