---
# This task file is itended to solve Requirements
# Solve issue https://docs.rke2.io/known_issues#firewalld
# Uninstall firewalld if installed
- name: Update Cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"
- name: Uninstall firewalld
  ansible.builtin.package:
    name: firewalld
    state: absent

# Solve issue https://docs.rke2.io/known_issues#networkmanager
# Check NetworkManager is installed on Debian
- name: Check if NetworkManager is installed
  ansible.builtin.shell:
    cmd: dpkg-query -l network-manager | tail -n 1 | cut -d' ' -f 1    
  register: network_manager_package
  changed_when: false
  when: ansible_facts['os_family'] == "Debian"

# Change Canal network provider to unmanaged in network manager when package is present.
- name: Verify Canal and Flannel Interface are ignored by NetworkManager
  ansible.builtin.copy:
    content: >
      [keyfile]
      unmanaged-devices=interface-name:cali*;interface-name:flannel*
    dest: /etc/NetworkManager/conf.d/rke2-canal.conf
    owner: root
    group: root
    mode: 0644
  when: '"ii" in network_manager_package.stdout or ansible_facts["os_family"] != "Debian"'

# Solve issue https://docs.rke2.io/known_issues#wicked
# Activate IP Forwared
- name: Verify IP Forward is in place
  ansible.builtin.copy:
    content: >
      net.ipv4.conf.all.forwarding=1
      net.ipv6.conf.all.forwarding=1
    dest: /etc/sysctl.d/90-rke2.conf
    owner: root
    group: root
    mode: 0644

# Solve issue https://docs.rke2.io/known_issues#canal-and-ip-exhaustion
# Install iptables
- name: Install iptables
  ansible.builtin.package:
    name: 
      - iptables
      - curl
      - wget
    state: present