---
# This task file is itended to solve Requirements
- name: Update Cache
  register: apt_cache_update
  changed_when: apt_cache_update is failed
  ansible.builtin.apt:
    update_cache: true

- name: Ensure firewalld is is Uninstalled
  ansible.builtin.apt:
    name: firewalld
    state: absent

- name: Ensure needed packages installed when airgap is false
  when: not rke2_airgap_install
  block:
    - name: Install and load kubctl package
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        state: present

    - name: Load sources
      ansible.builtin.apt_repository:
        repo: deb https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
        filename: kubernetes.list
        state: present

    - name: Install Kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present

- name: Install iptables
  ansible.builtin.apt:
    name:
      - iptables
      - ca-certificates
      - apt-transport-https
      - curl
      - wget
      - pgpgpg
    state: present
