- name: Uncordon {{ inventory_hostname }}
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  when: rke2_installed
  kubernetes.core.k8s_drain:
    name: "{{ inventory_hostname }}"
    kubeconfig: "{{ playbook_dir }}/rke2.yaml"
    state: uncordon
