- name: Drein node
  connection: local
  delegate_to: localhost
  kubernetes.core.k8s_drain:
    name: "{{ inventory_hostname }}"
    kubeconfig: "{{ rke2_kubeconfig | default('~/.kube/config') }}"
    state: drain
    pod_selectors:
      - 'app!=csi-attacher'
      - 'app!=csi-provisioner'
      - 'longhorn.io/component!=instance-manager'
    delete_options:
      ignore_daemonsets: true
      delete_emptydir_data: true
