# Download the install Script
- name: Download RKE2 install.sh
  ansible.builtin.get_url:
    url: "{{ channel_url }}"
    dest: "{{ install_sh }}"
    mode: 0755
    owner: root
    group: root
  when: update

# Install Script for Server
- name: Execute install Script
  ansible.builtin.command:
    cmd: "{{ install_sh }}"
  register: install_sh_out
  environment:
    INSTALL_RKE2_TYPE: "{{ rke2_type }}"
    INSTALL_RKE2_CHANNEL: "{{ channel }}"
  when: update
  notify:
    - "Restart rke2"

- name: Check if RKE2 is Started and enabled
  throttle: 1
  ansible.builtin.service:
    name: "rke2-{{ rke2_type }}"
    enabled: true
    state: started