- name: Drein node
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  when: rke2_installed
  kubernetes.core.k8s_drain:
    name: "{{ inventory_hostname_short }}"
    kubeconfig: "{{ playbook_dir }}/rke2.yaml"
    state: drain
    pod_selectors:
      - 'app!=csi-attacher'
      - 'app!=csi-provisioner'
      - 'longhorn.io/component!=instance-manager'
      - 'app.kubernetes.io/name=ingress-nginx'
    delete_options:
      ignore_daemonsets: true
      delete_emptydir_data: true
