- name: Cordon {{ inventory_hostname }}
  kubernetes.core.k8s_drain:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    name: "{{ inventory_hostname }}"
    state: cordon

- name: Drain "{{ inventory_hostname }}"
  kubernetes.core.k8s_drain:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    delete_options:
      ignore_daemonsets: true
      delete_emptydir_data: true
      terminate_grace_period: 10
      wait_timeout: 15
    state: drain
    name: "{{ inventory_hostname }}"
