# Download the install Script
- name: Download RKE2 install.sh
  ansible.builtin.get_url:
    url: "{{ channel_url }}"
    dest: "{{ install_sh }}"
    mode: 0755
    owner: root
    group: root
  when: update

# Install Script for Server
- name: Execute install Script
  ansible.builtin.command:
    cmd: "{{ install_sh }}"
  register: install_sh_out
  environment:
    INSTALL_RKE2_TYPE: "{{ rke2_type }}"
    INSTALL_RKE2_CHANNEL: "{{ channel }}"
  when: update
  notify:
    - "Restart rke2"

# Template Config file with the Values from default or passed by playbook and Inventorie
- name: Template Config file
  ansible.builtin.template:
    src: "{{ template_config }}"
    dest: "{{ config_file }}"
    mode: 0644
    owner: root
    group: root
  notify:
    - "Restart rke2"

- name: Verfiy RKE2 systemd service is started and enabled
  ansible.builtin.service:
    name: "rke2-{{ rke2_type }}"
    enabled: true
    state: started

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Replace 127.0.0.1 in kube.conf
  ansible.builtin.replace:
    path: /etc/rancher/rke2/rke2.yaml
    regexp: "127.0.0.1"
    replace: "{{ cluster_fqdn }}"
  when: '"server" in rke2_type'
