- name: Cordon {{ inventory_hostname }}
  kubernetes.core.k8s_drain:
    name: "{{ inventory_hostname }}"
    state: cordon

- name: Drain "{{ inventory_hostname }}"
  kubernetes.core.k8s_drain:
    state: drain
    name: "{{ inventory_hostname }}"
