- name: Cordon {{ inventory_hostname }}
  connection: local
  delegate_to: localhost
  kubernetes.core.k8s_drain:
    kubeconfig: "{{ rke2_kubeconfig | default('~/.kube/config') }}"
    name: "{{ inventory_hostname }}"
    state: uncordon
