---
# get actual channel version
# Block to get Version
- name: Get channel list
  ansible.builtin.uri:
    url: https://update.rke2.io/v1-release/channels
    method: GET
    follow_redirects: true
    return_content: true
    body: json
    status_code:
      - 503
      - 200
  register: rke2_version_list

- name: Get installed version from node
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      rke2 --version | cut -d ' ' -f 3 | head -n1 || echo "not installed"
    executable: /bin/bash
  changed_when: '"not installed" in rke2_installed_version.stdout'
  register: rke2_installed_version

- name: Set version as fact
  ansible.builtin.set_fact:
    rke2_latest_version: "{{ rke2_version_list.content | from_json | community.general.json_query(rke2_version_query) }}"
  vars:
    rke2_version_query: "data[?id=='{{ rke2_channel }}'].latest"
  when: rke2_version_list.status != 503

- name: Set version as fact
  ansible.builtin.set_fact:
    rke2_latest_version: "{{ rke2_installed_version | list }}"
  when: rke2_version_list.status == 503

- name: Change rke2 installed
  ansible.builtin.set_fact:
    rke2_installed: true
  when: not rke2_installed_version.changed

- name: Change update Status
  ansible.builtin.set_fact:
    rke2_update: true
  when:
    - rke2_check_update
    - 'rke2_installed_version.changed or rke2_latest_version[0] != rke2_installed_version.stdout'
    - rke2_version_list.status != 503
