---
# Master.yml
# Check Conf file exists
# Create Directory for Config

- name: Set primary Server as fact
  loop: "{{ anbsible_play_hosts_all }}"
  delegate_to: "{{ item }}"
  when: hostvars[item].rke2_primary
  ansible.builtin.set_fact:
    primary_node: "{{ item }}"

# RKE2 Check Token file exists
- name: Check RKE2 Token File
  register: token_stat
  delegate_to: "{{ primary_node }}"
  ansible.builtin.stat:
    path: "{{ rke2_token_file }}"

# RKE2 Token auslesen
- name: Read RKE2 Token File
  delegate_to: "{{ primary_node }}"
  when: token_stat.exists
  register: token_b64
  ansible.builtin.slurp:
    path: "{{ rke2_token_file }}"

# Read Token value to facts
- name: Set token to facts for all
  when: token_b64.content is defined and not rke2_primary
  ansible.builtin.set_fact:
    rke2_token: "{{ token_b64.content | b64decode }}"

# Read Token value to facts
- name: Set token to facts for primary
  ansible.builtin.set_fact:
    rke2_token: "{{ rke2_token | split(':') | last }}"
  when: rke2_primary and rke2_token is defined

  # Read Token value to facts
- name: Set token to facts
  ansible.builtin.set_fact:
    rke2_token: "{{ lookup('community.general.random_string', special=false, length=32) }}\n"
  when: rke2_primary and rke2_token is undefined
