---
- name: Converge
  hosts: all
  become: true
  remote_user: molecule
  vars:
    cluster_fqdn: "ansible-rke2-api-svc.devops.svc.cluster.local"
  tasks:
    - name: "Include bechtle.rke2"
      ansible.builtin.include_role:
        name: "bechtle.rke2"
