---
- name: Converge
  hosts: all
  become: true
  remote_user: molecule
  tasks:

    - name: "Include bechtle.rke2"
      vars:
        rke2_cluster_fqdn: "{{ inventory_hostname }}.devops.svc.cluster.local"
      ansible.builtin.include_role:
        name: "bechtle.rke2"
