---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml
platforms:
  - name: ansible-rke2-server-1
    namespace: devops
    memory: "4Gi"
    storage_size: "10Gi"
    container_image: docker://registry.gitlab-bs.demolab.ch:4567/kubevirt/kubevirt-images/virt-image-debian-11:latest
    ssh_service:
      type: ClusterIP
    custom_manifest:
      - apiVersion: v1
        kind: Service
        metadata:
          name: ubuntu
          namespace: devops
        spec:
          type: ClusterIP
          ports:
            - protocol: TCP
              port: 6443
              targetPort: 6443

    # dataVolumeTemplates:
    #   - metadata:
    #       name: pvc-nsible-rke2-server-1
    #       namespace: devops
    #     spec:
    #       pvc:
    #         accessModes:
    #           - ReadWriteOnce
    #         resources:
    #           requests:
    #             storage: 20Gi
    #       preallocation: true
    #       source:
    #         registry:
    #           url: docker://registry.gitlab-bs.demolab.ch:4567/kubevirt/kubevirt-images/virt-image-debian-11:latest
    # volumes:
    #   - name: boot
    #     dataVolume:
    #       name: pvc-nsible-rke2-server-1
    # ssh_service:
    #   type: ClusterIP
  # - name: ansible-rke2-agent-1
  #   namespace: devops
  #   molecule_user: molecule
  #   volumes:
  #     - name: boot
  #       containerDisk:
  #         image: registry.gitlab-bs.demolab.ch:4567/kubevirt/kubevirt-images/virt-image-debian-11:latest
  #         path: /disk/debian-11.qcow2
  #   ssh_service:
  #     type: ClusterIP
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      ansible-rke2-server-1:
        rke2_type: server
        rke2_primary: true
        fqdn: "{{ inventory_name }}.example.com"
      # ansible-rke2-agent-1:
      #   rke2_type: agent
      #   fqdn: "{{ inventory_name }}.example.com"
verifier:
  name: ansible
